### ISSUE TITLE
todo 0.1.0

### ISSUE THREAD

**Issue by bee-san** [HashPals/Name-That-Hash#1]
- [x] Tryhackme test (make sure all hashes are popular)
- [x] Upload to AUR etc etc
- [x] spell check readme
- [x] Bug where `$2y$12$Dwt1BZj6pcyc3Dy1FWZ5ieeUznr71EeNkJkUlypTsgbX1H68wsRom` gets stripped and broken.
- [x] Greppable output
- [x] Pretty output
- [x] Typehints
- [x] File Input
- [x] Write tests
- [x] Design README
- [x] Design logo
- [x] Help menu on no args
- [x] Fill out hash descriptions
- [x] Write documentation
- [x] Gifs (terminaliser)
- [x] Pypi upload
- [x] Add docs for editing hashes / adding new ones
- [x] Add badges to readme
- [x] Add github bots (image compression)
- [x] Add blackouts descriptiosn
- [x] Add support for $6$ etc

- [x] Script to active on `name-that-hash` too
- [x] Remove set from inner loop
- [x] optimise regex lookup and fix top 10 bug

HashInfo(name="SHA-512" hashcat=1700 john="RAW-SHA-512" extended=False, description="This is used in the the bitcoin blockchain").
HashInfo(name="SHA-256" Hashcat=1400 John="Raw-SHA256" extended=False description="256-bit key and is a good partner-function for AES")
With NTLM you could add to the description that it uses md4/md5 hashing algos

Fix visual bug 
![image](https://user-images.githubusercontent.com/10378052/105739572-28a67a80-5f30-11eb-850c-47a5fd6c23bc.png)
^^ fixed
We support $6$
![image](https://user-images.githubusercontent.com/10378052/105739928-918df280-5f30-11eb-8a98-56703c240cde.png)
^^ fixed
